### ISSUE TITLE
Finish self healing code

### ISSUE THREAD

**Issue by ormris** [senior-design-crowd/crowdify#19]

**Comment by mffigueroa** [comment]
I've added the self-healing code, but I'm still working on correcting my implementation. Last week I spent a bit of time adding more logging of this portion of the code so I can understand what's happening. The neighbor nodes are all correctly detecting when a node goes down. Ultimately it comes down to correctly negotiating between the various neighbor nodes as to who will take over the part of the network occupied by the down node.

**Comment by mffigueroa** [comment]
Ex node takeover logs so far:

Node #1	Neighbor node #9 died.
	Hasn't updated us for 5002 ms.
	Node has DHT area of size 0.125	Taking over node in 250 ms.
Node #3	Neighbor node #9 died.
	Hasn't updated us for 5003 ms.
	Node has DHT area of size 0.03125	Taking over node in 62.5 ms.
Node #5	Neighbor node #9 died.
	Hasn't updated us for 5003 ms.
	Node has DHT area of size 0.03125	Taking over node in 62.5 ms.
Node #3	Taking over neighbor node #9.
	63 ms has passed since its death.
	Node takeover request:
		Node num: 9
		My DHT Area: 
			Left: 0.25
			Right: 0.5
			Top: 0.75
			Bottom: 0.875
Node #3	Sending node takeover request to 1.
Node #5	Taking over neighbor node #9.
	64 ms has passed since its death.
	Node takeover request:
		Node num: 9
		My DHT Area: 
			Left: 0.25
			Right: 0.5
			Top: 0.875
			Bottom: 1
Node #3	Sending node takeover request to 5.
Node #5	Sending node takeover request to 1.
Node #5	Sending node takeover request to 3.
Node #1	Got MPI message from 3: NODE_TAKEOVER_REQUEST
Node #1		Node takeover request:
		Node num: 9
		DHT Area: 
			Left: 0.25
			Right: 0.5
			Top: 0.75
			Bottom: 0.875
Node #1	Resolving node takeover request from 3 for 9
	Node 9 was detected as a dead neighbor.
Node #1		Comparing our DHT area with that of node 3
	Node 3 has a lesser or equal DHT area than us, responding to them with CAN_TAKEOVER message.
Node #1	Got MPI message from 3: NODE_TAKEOVER_REQUEST
Node #3	Got MPI message from 5: NODE_TAKEOVER_REQUEST
Node #3		Node takeover request:
		Node num: 9
		DHT Area: 
			Left: 0.25
			Right: 0.5
			Top: 0.875
			Bottom: 1
Node #3	Resolving node takeover request from 5 for 9
	Node 9 was detected as a dead neighbor.
Node #3		Comparing our DHT area with that of node 5
	Node 5 has a lesser or equal DHT area than us, responding to them with CAN_TAKEOVER message.
Node #3	Got MPI message from 5: NODE_TAKEOVER_REQUEST
Node #1		Node takeover request:
		Node num: 9
		DHT Area: 
			Left: 0.25
			Right: 0.5
			Top: 0.875
			Bottom: 1
Node #5	Got MPI message from 3: NODE_TAKEOVER_REQUEST
Node #1	Resolving node takeover request from 5 for 9
	Node 9 was detected as a dead neighbor.
Node #5		Node takeover request:
		Node num: 9
		DHT Area: 
			Left: 0.25
			Right: 0.5
			Top: 0.75
			Bottom: 0.875
Node #1		Comparing our DHT area with that of node 5
	Node 5 has a lesser or equal DHT area than us, responding to them with CAN_TAKEOVER message.
Node #5	Resolving node takeover request from 3 for 9
	Node 9 was detected as a dead neighbor.
Node #5		Comparing our DHT area with that of node 3
	Node 3 has a lesser or equal DHT area than us, responding to them with CAN_TAKEOVER message.
Node #5	Got MPI message from 3: NODE_TAKEOVER_REQUEST
Node #1	Got MPI message from 5: NODE_TAKEOVER_REQUEST

**Comment by mffigueroa** [comment]
The self-healing works under normal conditions it seems. I currently have it set so that nodes will consider their neighbors to be dead if they don't send an update for 5 seconds and the debugging node is adding and removing nodes to the network every 7 seconds, so its a pretty tight window. 
And under that tight window, the network managed to stay consistent for 91 frames, as can be seen here:
![dht_frame91](https://cloud.githubusercontent.com/assets/3539159/13547080/f22bf398-e277-11e5-91cf-abc971228d5c.png)

However, the frames after that the network becomes inconsistent. Here is the 173rd frame:
![dht_frame173](https://cloud.githubusercontent.com/assets/3539159/13547083/0283ff42-e278-11e5-894e-771efacf5836.png)

Note there is a new frame to every change to the DHT network, like if a node dies or a new node joins. Although sometimes multiple changes can happen in one frame.

**Comment by mffigueroa** [comment]
Since I'm moving on at the moment from writing self-healing code and it's working in its basic form, I'm closing this issue.
